In [215]:
##This script was used for obtaining the results broken down into categories

##This takes the "score file" and the "order of categories file" and says the percentage within each category.
##It also says how many clusters we have in each category
##Careful changing the "NAME OF RANDOM ORDER OF CATEGORIES1.TXT" to RANDOM ORDER OF CATEGORIES2.TXT

In [216]:
cd C:\Users\Yoo\Desktop\summerProject\hmmer-3.2.1\trial\usefulFiles\breakingDownCategories\resultsBrokenDownByCategory

C:\Users\Yoo\Desktop\summerProject\hmmer-3.2.1\trial\usefulFiles\breakingDownCategories\resultsBrokenDownByCategory


In [227]:
nameOfTheScoreFile = "score10.npy"
positionCategoryDictionary = {}#Will store a list of the positions for each category
numberOfClustersPerCategory = {}
i=0
## Max I and Min I are chosen according to the test clusters position.
## This is just because several score.npy files were created from 1 to 10 as there were two experiments with 5 subsets each. We want to know which clusters were chosen in each subset depending on the scores file name.
## Additionally, the first experiment used "NAME OF RANDOM ORDER OF CATEGORIES1.TXT" for score1 till score5 and the second one used NAME OF RANDOM ORDER OF CATEGORIES2.TXT from score6 till score10.npy
## It is important to know which clusters are in each subset given that the file "orderOfCategories" had assigned the category for each cluster depending on the order.
if (int(nameOfTheScoreFile[-5])%5)==1:  
    maxI=206
    minimumI=0
elif (int(nameOfTheScoreFile[-5])%5)==2:  
    maxI=412
    minimumI=206
elif (int(nameOfTheScoreFile[-5])%5)==3:  
    maxI=618
    minimumI=412
elif (int(nameOfTheScoreFile[-5])%5)==4:  
    maxI=824
    minimumI=618
elif (int(nameOfTheScoreFile[-5])%5)==0:  
    maxI=1031
    minimumI=824

In [228]:
orderOfCategoriesFile = open ("randomOrderOfCategories2.txt")
for line in orderOfCategoriesFile:
    if i>=maxI or i<minimumI:
        i+=1
        continue
    category = line.strip("\n")
    if category not in numberOfClustersPerCategory:
        numberOfClustersPerCategory[category]=1
        positionCategoryDictionary[category]=[i-minimumI]##Creates a list ##We put -minimum I as in the score matrix the positions start from 0 always
    else:
        numberOfClustersPerCategory[category] +=1
        positionCategoryDictionary[category].append(i-minimumI)
        ## We put -minimum I as in the score matrix, the positions start from 0 always 
        ## (It's size it's the same than the size of the test size, while in random order
        ## of categories we have the 1031 clusters. Don't forget that we use the same file
        ## for 5 crossvalidation experiments, so that file has all the clusters and we take
        ## the ones from the test set according to the name of the score file)
    i +=1
orderOfCategoriesFile.close()

In [229]:
import numpy as np
score = np.load(nameOfTheScoreFile)
dimension = len (score)
pos = np.zeros(dimension)
for i in range (0, dimension):
    pos[i] = 1
    selfScore = score[i][i]
    for j in range (0, dimension):##Checking the score with the 206 clusters of the test set
        if score[i][j]>selfScore:##With greater than, we ignore same scores of clusters that produce the same molecule (included when we check [i][i])
            pos[i]+=1##Every time we find a greater score, the ranking of the self score is reduced

In [230]:
print (numberOfClustersPerCategory)

{'Nucleoside': 1, 'NRP': 68, 'Polyketide': 56, 'Alkaloid': 7, 'Other': 32, 'Saccharide': 15, 'RiPP': 11, 'Terpene': 17}


In [231]:
for category in sorted(positionCategoryDictionary.keys()):
    listOfPos = positionCategoryDictionary[category]
    print ("RESULTS FOR THE CATEGORY: "+ category.upper())
    print ("Clusters in the test set = "+ str(len(listOfPos)))
    listOfPos= positionCategoryDictionary[category]
    print ("TOP 1:  %.2f%% ( %d out of %d )" % (sum(pos[i]==1 for i in listOfPos)/len(listOfPos)*100, sum(pos[i]==1 for i in listOfPos), len(listOfPos)))
    print ("TOP 3:  %.2f%% ( %d out of %d )" % (sum(pos[i]<=3 for i in listOfPos)/len(listOfPos)*100, sum(pos[i]<=3 for i in listOfPos), len(listOfPos)))
    print ("TOP 5:  %.2f%% ( %d out of %d )" % (sum(pos[i]<=5 for i in listOfPos)/len(listOfPos)*100, sum(pos[i]<=5 for i in listOfPos), len(listOfPos)))
    print ("TOP 10: %.2f%% ( %d out of %d )" % (sum(pos[i]<=10 for i in listOfPos)/len(listOfPos)*100, sum(pos[i]<=10 for i in listOfPos), len(listOfPos)))
    print ("TOP 25: %.2f%% ( %d out of %d )" % (sum(pos[i]<=25 for i in listOfPos)/len(listOfPos)*100, sum(pos[i]<=25 for i in listOfPos), len(listOfPos)))
    print ("**************************")

RESULTS FOR THE CATEGORY: ALKALOID
Clusters in the test set = 7
TOP 1:  28.57% ( 2 out of 7 )
TOP 3:  42.86% ( 3 out of 7 )
TOP 5:  42.86% ( 3 out of 7 )
TOP 10: 42.86% ( 3 out of 7 )
TOP 25: 42.86% ( 3 out of 7 )
**************************
RESULTS FOR THE CATEGORY: NRP
Clusters in the test set = 68
TOP 1:  36.76% ( 25 out of 68 )
TOP 3:  41.18% ( 28 out of 68 )
TOP 5:  42.65% ( 29 out of 68 )
TOP 10: 50.00% ( 34 out of 68 )
TOP 25: 64.71% ( 44 out of 68 )
**************************
RESULTS FOR THE CATEGORY: NUCLEOSIDE
Clusters in the test set = 1
TOP 1:  0.00% ( 0 out of 1 )
TOP 3:  0.00% ( 0 out of 1 )
TOP 5:  0.00% ( 0 out of 1 )
TOP 10: 0.00% ( 0 out of 1 )
TOP 25: 0.00% ( 0 out of 1 )
**************************
RESULTS FOR THE CATEGORY: OTHER
Clusters in the test set = 32
TOP 1:  37.50% ( 12 out of 32 )
TOP 3:  40.62% ( 13 out of 32 )
TOP 5:  43.75% ( 14 out of 32 )
TOP 10: 50.00% ( 16 out of 32 )
TOP 25: 65.62% ( 21 out of 32 )
**************************
RESULTS FOR THE CATEGORY:

In [171]:
##Prints the number of times
print (sum(pos==1))
print (sum(pos<=3))
print (sum(pos<=5))
print (sum(pos<=10))
print (sum(pos<=25))

84
101
111
125
152


In [172]:
##Prints the percentages
print ("The percentage of times in position 1 is %.2f%%" % (sum(pos==1)/dimension*100))
print ("The percentage of times in TOP 3 is %.2f%%" % ((sum(pos==1)+sum(pos==2)+sum(pos==3))/dimension*100))
print ("The percentage of times in TOP 5 is %.2f%%" % (sum(pos<=5)/dimension*100))
print ("The percentage of times in TOP 10 is %.2f%%" % (sum(pos<=10)/dimension*100))
print ("The percentage of times in TOP 25 is %.2f%%" % (sum(pos<=25)/dimension*100))

The percentage of times in position 1 is 40.78%
The percentage of times in TOP 3 is 49.03%
The percentage of times in TOP 5 is 53.88%
The percentage of times in TOP 10 is 60.68%
The percentage of times in TOP 25 is 73.79%


In [173]:
print (score)

[[0.63179326 0.13364721 0.1255894  ... 0.18206134 0.08733822 0.04914435]
 [0.18036018 0.226484   0.24135417 ... 0.22551402 0.20099427 0.09830681]
 [0.15268682 0.27767353 0.96525295 ... 0.24991682 0.30118017 0.14013778]
 ...
 [0.11249782 0.16514626 0.12692043 ... 0.3476478  0.12741186 0.08238677]
 [0.10849376 0.13694131 0.27087628 ... 0.21069483 0.92211396 0.13848082]
 [0.18214418 0.26971613 0.22410504 ... 0.19673955 0.15316593 0.69820017]]


In [73]:
print (pos)

[  1.  29.   1.   1.   1. 104.  23.   9.  43.   1.   1. 130.   1.  22.
 121.   1.   1.  60.   1.   1.   8.   1.  20.  29.  12.  41.   2.  12.
   1.   1.   1.  17. 105.   1.  36.  16.  75.   2.   1.   5. 206.   5.
   4.  86. 101.   1.   3.   1. 101.   1.   2.   1.   1.   4. 122.   1.
  17.  41.   1.  63.   1.   7.  18.   1.   1.  29.  20.  70.  27.  51.
   1.  34.   1.   1.   1.   1.  53.   1.  82.   1.  86.   1.   5.   1.
  18.   1.   1.  13.   1.   1.  26.  13.   1.   2.   1.  87.   1.  57.
   1.   1.   1.  10.   1.   4.   1.   1.   1. 110.   5.  22.  72.   2.
  32.  22.   1.   1.   1.  12.   1. 148.   5.   3.   1.   4.   7.  11.
   1.   1.   1.  69.  23.   1.   3.   2.   1.   1.   1. 119. 137.   1.
   1. 153.   4.   6.   1.  60.  22.   1.  66.   1.   1.  22.  24.  19.
   1.   8.   1.   1.  63.   1.   1.   1.   1.   1.  24.  13.   1.  61.
  15.  20.  41.  34.   6.  35.   1.   1.  36.   1.   1.   1.   6.   1.
  15.  52.  80.  18.   1.   6.   1. 133.  66.   1.  30. 205.  37.  55.
 148. 